spring.application.name=kafka-producer-service
server.port=8081
spring.kafka.bootstrap-servers=localhost:9092,localhost:9192

spring.kafka.producer.properties.metadata.max.age.ms=300000

#Asking broker to reply only when all ISR successfully get the events
spring.kafka.producer.acks=all

#Serializer -> Partition -> Record Accumulator -> Compression -> Sender Thread

#----SERIALIZER-------
#Key: needs to be string
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
#spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

#Value: Custom Serializer
#spring.kafka.producer.value-serializer=com.example.kafka.config.OrderSummarySerializer
#---------------------

#-----RECORD ACCUMULATOR------

#Max batch size, send when batch reaches 32kb (Even if linger.ms hasn't expired) 
spring.kafka.producer.properties.batch.size=32768

#Batching, wait 20ms to collect more messages before sending
spring.kafka.producer.properties.linger.ms=20

#Total buffer memory for all batches: 32MB (if full, send() will get blocked till space created or max block time)
spring.kafka.producer.properties.buffer.memory=33554432

#Max time send() blocks if buffer is full (default 60s), after this time, send() call will fail immediately
spring.kafka.producer.properties.max.block.ms=60000

#--------COMPRESSION-------

#cOMPRESS ENTIRE BATCH BEFORE SENDING
spring.kafka.producer.properties.compression.type=snappy


#---------SENDER THREAD------

#Retry on transient failures (network timeout, leader change, etc., )
spring.kafka.producer.retries=3

#Max in-flight requests
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5



spring.kafka.producer.properties.enable.idempotence=true

spring.kafka.producer.properties.request.timeout.ms=30000

spring.kafka.producer.properties.delivery.timeout.ms=120000