spring.application.name=kafka-consumer-service

spring.port=8082

spring.kafka.bootstrap-servers=localhost:9092, localhost:9192
# Which group consumer needs to join 
spring.kafka.consumer.group-id=order-consumer-group

#Should be same what at Producer we have selected
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
#We used the below for manual mapping
#spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

#Since we have selected JSON Deserializer, we need to tell the default type in which this JSON need to be converted to
#spring.kafka.consumer.properties.spring.json.value.default.type=com.kafkatutorial.model.Order

#spring.kafka.consumer.properties.spring.json.use.type.headers=false

#spring.kafka.consumer.properties.spring.json.type.mapping=com.example.kafka.model.Order:com.kafkatutorial.model.Order, com.example.kafka.model.Payment:com.kafkatutorial.model.Payment

spring.kafka.consumer.properties.spring.json.use.type.headers=false 

spring.kafka.consumer.properties.spring.json.value.default.type=com.kafkatutorial.model.Order